opcua:
  endpoint: "opc.tcp://192.168.178.230:4840"
  nodes:
    conductivity_ch1: 'ns=2;s="Conductivity_Ch1"'
    conductivity_ch2: 'ns=2;s="Conductivity_Ch2"'
    conductivity_ch3: 'ns=2;s="Conductivity_Ch3"'
    conductivity_ch4: 'ns=2;s="Conductivity_Ch4"'

ethernetip:
  ip_address: "192.168.178.237"
  eds_file: "./eds_files/MT_M800_1P_EIP_V1.2_20200107.eds"