opcua:
  endpoint: "opc.tcp://192.168.178.230:4840"
  nodes:
    conductivity_ch1: 'ns=2;s=TWIN_PL/.M800/Conductivity_Ch1'
    temperature_ch1: 'ns=2;s=TWIN_PL/.M800/Temperature_Ch1'
    status_ch1: 'ns=2;s=TWIN_PL/.M800/Status_Ch1'
    conductivity_ch2: 'ns=2;s=TWIN_PL/.M800/Conductivity_Ch2'
    temperature_ch2: 'ns=2;s=TWIN_PL/.M800/Temperature_Ch2'
    status_ch2: 'ns=2;s=TWIN_PL/.M800/Status_Ch2'
    conductivity_ch3: 'ns=2;s=TWIN_PL/.M800/Conductivity_Ch3'
    temperature_ch3: 'ns=2;s=TWIN_PL/.M800/Temperature_Ch3'
    status_ch3: 'ns=2;s=TWIN_PL/.M800/Status_Ch3'
    conductivity_ch4: 'ns=2;s=TWIN_PL/.M800/Conductivity_Ch4'
    temperature_ch4: 'ns=2;s=TWIN_PL/.M800/Temperature_Ch4'
    status_ch4: 'ns=2;s=TWIN_PL/.M800/Status_Ch4'
    watchdog: 'ns=2;s=TWIN_PL/.M800/WATCHDOG'

ethernetip:
  ip_address: "192.168.178.237"
  eds_file: "./eds_files/MT_M800_1P_EIP_V1.2_20200107.eds"